// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkLa5jf5jg4ZdTRjUeJpG1ISvfgxLOdK0',
    appId: '1:617858400184:web:c976666133dc28aacd594d',
    messagingSenderId: '617858400184',
    projectId: 'isim-sehir-multiplayer',
    authDomain: 'isim-sehir-multiplayer.firebaseapp.com',
    storageBucket: 'isim-sehir-multiplayer.firebasestorage.app',
    measurementId: 'G-BLFY2RTJV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMdVzNAPVDVD8qY1NOM9_wXWMcJOndTjA',
    appId: '1:617858400184:android:9e75b5cc98c3fb7acd594d',
    messagingSenderId: '617858400184',
    projectId: 'isim-sehir-multiplayer',
    storageBucket: 'isim-sehir-multiplayer.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5iYit7QkCDsJjNsN6E6WBfePIJBB5azg',
    appId: '1:617858400184:ios:936857d5af4e4ccbcd594d',
    messagingSenderId: '617858400184',
    projectId: 'isim-sehir-multiplayer',
    storageBucket: 'isim-sehir-multiplayer.firebasestorage.app',
    iosBundleId: 'com.tamam.isim_sehir_hayvan',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5iYit7QkCDsJjNsN6E6WBfePIJBB5azg',
    appId: '1:617858400184:ios:8295014c4b508cb4cd594d',
    messagingSenderId: '617858400184',
    projectId: 'isim-sehir-multiplayer',
    storageBucket: 'isim-sehir-multiplayer.firebasestorage.app',
    iosBundleId: 'com.example.isimSehirHayvan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkLa5jf5jg4ZdTRjUeJpG1ISvfgxLOdK0',
    appId: '1:617858400184:web:9497eed1aeaf01a0cd594d',
    messagingSenderId: '617858400184',
    projectId: 'isim-sehir-multiplayer',
    authDomain: 'isim-sehir-multiplayer.firebaseapp.com',
    storageBucket: 'isim-sehir-multiplayer.firebasestorage.app',
    measurementId: 'G-YW3R3YGBXJ',
  );
}
